language: c++

before_install:
    - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get update


install:
    - sudo apt-get install gcc-4.8 g++-4.8

script: make

notifications:
    email: false